// Main process engine services
export { agentService, UnifiedAgentService } from './unifiedAgent';
export type {
  AgentConfig,
  AgentEngineType,
  AcpSessionStatus,
  MessageWithParts,
  PromptOptions,
  CommandOptions,
  SdkSession,
  SessionStatus,
  ToolInfo,
  ProviderInfo,
  Message,
  Part,
  UserMessage,
  AssistantMessage,
  TextPart,
  ReasoningPart,
  FilePart,
  ToolPart,
  StepStartPart,
  StepFinishPart,
  SnapshotPart,
  PatchPart,
  TextPartInput,
  FilePartInput,
  FileDiff,
} from './unifiedAgent';
export { AcpEngine } from './acp/acpEngine';
export {
  createAcpConnection,
  loadAcpSdk,
  resolveAcpBinary,
  type AcpConnectionConfig,
  type AcpConnectionResult,
  type AcpClientSideConnection,
  type AcpClientHandler,
  type AcpSessionUpdate,
  type AcpAgentMessageChunk,
  type AcpAgentThoughtChunk,
  type AcpToolCall,
  type AcpToolCallUpdate,
  type AcpSessionInfoUpdate,
  type AcpUsageUpdate,
  type AcpPermissionOption,
  type AcpPermissionOptionKind,
  type AcpPermissionRequest,
  type AcpPermissionResponse,
  type AcpEnvVariable,
  type AcpHttpHeader,
  type AcpMcpServer,
  type AcpSdkModule,
} from './acp/acpClient';
export { mapAgentCommand, resolveAgentEnv } from './agentHelpers';
export {
  isEngineInstalledLocally,
  findEngineBinary,
  createIsolatedEnvironment,
  getEngineStatus,
  type AgentEngine,
  type EngineConfig,
  type EngineStatus,
} from './engineManager';
