name: Continuous Deployment

on:
  # 暂时禁用 tag 自动触发，仅保留手动触发
  # push:
  #   tags:
  #     - 'crate-v*'
  workflow_dispatch:

permissions: read-all

jobs:
  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
